/**
 * GrowthHunter — Multi-Tenant & RBAC Permissions System
 */

export const USER_ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  SALES: "SALES",
  ANALYST: "ANALYST"
};

export const ROLE_PERMISSIONS = {
  OWNER: ["ALL"],
  ADMIN: ["ADMINISTRATION", "MANAGE_USERS", "SETTINGS", "EXPORT_DATA", "DELETE_LEADS"],
  MANAGER: ["MANAGE_TEAM", "MANAGE_CAMPAIGNS", "REPORTS", "VIEW_ALL_LEADS", "PIPELINE_WRITE"],
  SALES: ["MY_LEADS", "CONVERSATIONS_WRITE", "TASKS_WRITE", "PIPELINE_MOVE", "WHATSAPP_SEND"],
  ANALYST: ["READ_ONLY", "REPORTS_READ", "LEAD_DIAGNOSIS_READ"]
};

export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  INTEGRATION_UPDATED: "INTEGRATION_UPDATED",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  PIPELINE_CHANGED: "PIPELINE_CHANGED",
  OWNER_CHANGED: "OWNER_CHANGED",
  COMPANY_DELETED: "COMPANY_DELETED",
  EXPORT_DATA: "EXPORT_DATA"
};
